mediatheque2/urls.py
from django.contrib import admin
from django.urls import path
from gestion import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.accueil, name='accueil'),
    path('contact/', views.contact, name='contact'),
    path('inscription/', views.inscription, name='inscription'),
    path('connexion/', views.connexion, name='connexion'),
    path('deconnexion/', views.deconnexion, name='deconnexion'),
    path('documents/', views.documents, name='documents'),
    path('reserver/<int:document_id>/', views.reserver_document, name='reserver_document'),
    path('mes_reservations/', views.mes_reservations, name='mes_reservations'),
    path('annuler_reservation/<int:reservation_id>/', views.annuler_reservation, name='annuler_reservation'),
    path('mon_compte/', views.mon_compte, name='mon_compte'),
]

gestion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import date


# créer un modèle pour le profil utilisateur
class ProfilUtilisateur(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_naissance = models.DateField(null=True, blank=True)
    ville = models.CharField(max_length=100, null=True, blank=True)
    scolarise_agglomeration = models.BooleanField(default=False)
    
    abonnement_valide = models.BooleanField(default=False)
    date_abonnement = models.DateField(default=timezone.now)  # Ajout date d'abonnement
    lettre_envoyee = models.BooleanField(default=False)  # Ajout lettre envoyée

    def age(self):
        today = timezone.now().date()
        if self.date_naissance:
            return today.year - self.date_naissance.year - (
                (today.month, today.day) < (self.date_naissance.month, self.date_naissance.day)
            )
        return None

    def gratuit(self):
        age = self.age()
        if age is None:
            return False
        return (
        (self.ville and self.ville.lower() == 'montpellier') or
        age < 12 or
        (age < 18 and self.scolarise_agglomeration))

    
    def get_tarif(self):
        if self.gratuit():
            return "Gratuit"
        else:
            return "Tarif normal : 22 € par an ou Tarif Reduit sur présentation de justificatif: 10,50 € par mois. "

    
    def __str__(self):
        return f"Profil de {self.user.username} - Abonnement {'Valide' if self.abonnement_valide else 'Non valide'}"

# Les différents types de documents
class Document(models.Model):
    TYPE_CHOICES = [
        ('livre', 'Livre imprimé'),
        ('cd', 'CD / Audio'),
        ('dvd', 'DVD / Blu-Ray'),
        ('magazine', 'Magazine / Périodique'),
    ]

    titre = models.CharField(max_length=200)
    auteur = models.CharField(max_length=200, blank=True, null=True)
    type_document = models.CharField(max_length=10, choices=TYPE_CHOICES)
    date_sortie = models.DateField(null=True, blank=True)
    genre = models.CharField(max_length=100, blank=True, null=True)
    nombre_pages = models.IntegerField(blank=True, null=True)  # pour livres
    duree_minutes = models.IntegerField(blank=True, null=True)  # pour CD, DVD
    disponible = models.BooleanField(default=True)


    def __str__(self):
        return self.titre

# Modèle pour gérer les emprunts de documents
class Emprunt(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    date_emprunt = models.DateField(default=timezone.now)
    date_retour_prevue = models.DateField()
    date_retour_reelle = models.DateField(blank=True, null=True)

    def get_date_retour_prevue():
        return timezone.now().date() + timedelta(days=4)

    def est_en_retard(self):
        return self.date_retour_reelle is None and self.date_retour_prevue < timezone.now().date()
    def __str__(self):
        return f"{self.utilisateur.username} a emprunté {self.document.titre}"


# Modèle pour créer une reservation
class Reservation(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)
    document = models.ForeignKey(Document, on_delete=models.CASCADE)
    date_reservation = models.DateField(default=date.today)
    date_venue = models.DateField()

    def __str__(self):
        return f"{self.utilisateur.username} réserve {self.document.titre} pour le {self.date_venue}"

gestion/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from datetime import datetime, timedelta, date
from .models import Document, Emprunt, Reservation
from .reservation_utils import est_date_disponible
from .models import ProfilUtilisateur
from django.utils import timezone



# Fonction pour vérifier si l'abonnement est valide
def abonnement_valide(user):
    try:
        profil = ProfilUtilisateur.objects.get(user=user)
        return profil.abonnement_valide
    except ProfilUtilisateur.DoesNotExist:
        return False


def accueil(request):
    return render(request, 'accueil.html')
def contact(request):
    return render(request, 'contact.html')

# Inscription et création de compte
def inscription(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        date_naissance = request.POST['date_naissance']
        ville = request.POST['ville']
        etudiant = request.POST.get('etudiant') == 'on'
        email = request.POST['email']
        password = request.POST['password']

        # Créer l'utilisateur
        user = User.objects.create_user(username=email, email=email, password=password, first_name=first_name, last_name=last_name)
        user.save()

        # Créer son profil automatiquement
        ProfilUtilisateur.objects.create(user=user, date_naissance=date_naissance, ville=ville, etudiant=etudiant)

        messages.success(request, "Votre compte a été créé ! Veuillez venir à la médiathèque pour activer votre abonnement.")
        return redirect('/connexion/')

    return render(request, 'inscription.html')

# Connexion de l'utilisateur    
def connexion(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')  # Redirige vers la page d'accueil après connexion
        else:
            messages.error(request, "Identifiants invalides. Veuillez réessayer.")
            return redirect('/connexion/')

    return render(request, 'connexion.html')

# Déconnexion de l'utilisateur
def deconnexion(request):
    logout(request)
    return redirect('/') 

# Page des documents si l'utilisateur est connecté et a payé son abonnement
@login_required
def documents(request):
    if not abonnement_valide(request.user):
        messages.info(request, "Vous pouvez consulter les documents mais vous devez être abonné pour réserver.")


    documents = Document.objects.all()
    date_choisie_str = request.GET.get('date_choisie')
    
    date_choisie = date.today()
    if date_choisie_str:
        try:
            date_choisie = date.fromisoformat(date_choisie_str)
        except ValueError:
            pass

    type_doc = request.GET.get('type_document')
    auteur = request.GET.get('auteur')
    genre = request.GET.get('genre')
    date_min = request.GET.get('date_min')  # nouveau
    duree_max = request.GET.get('duree_max')  # nouveau

    if type_doc:
            documents = documents.filter(type_document=type_doc)
    if auteur:
            documents = documents.filter(auteur__icontains=auteur)
    if genre:
            documents = documents.filter(genre__icontains=genre)
    if date_min:
            documents = documents.filter(date_sortie__gte=date_min)  # >= la date choisie
    if duree_max:
            documents = documents.filter(duree_minutes__lte=duree_max)  # <= la durée max


    documents_info = []
    today = date.today()

    for doc in documents:
        reservations = Reservation.objects.filter(document=doc)
        dispo = True
        for resa in reservations:
            debut = resa.date_venue
            fin = debut + timedelta(days=3)
            if debut <= today <= fin:
                dispo = False
                break
        documents_info.append({
            'document': doc,
            'disponible': dispo,
        })

    return render(request, 'documents.html', {'documents_info': documents_info, 'abonnement_valide': abonnement_valide(request.user),})

# Page de réservation d'un document si l'utilisateur est connecté et a payé son abonnement
@login_required
def reserver_document(request, document_id):
    if not abonnement_valide(request.user):
        messages.error(request, "Votre abonnement n'est pas encore activé. Merci de venir à la médiathèque.")
        return redirect('accueil')
    
    document = Document.objects.get(id=document_id)

    if request.method == 'POST':
        date_venue_str = request.POST.get('date_venue')
        date_venue = datetime.strptime(date_venue_str, "%Y-%m-%d").date()

        reservations_en_cours = Reservation.objects.filter(utilisateur=request.user, date_venue__gte=date.today()).count()

        # Bloquer à 4 réservations maximum en même temps par abonné 
        if reservations_en_cours >= 4:
            messages.error(request, "Vous avez déjà atteint la limite de 4 emprunts. Merci de rendre un document avant de réserver un nouveau.")
            return render(request, 'reserver.html', {'document': document})
        
        # Vérifier si la date est valide
        if not est_date_disponible(document, date_venue):
            messages.error(request, "Ce document est déjà réservé sur cette période. Merci de choisir une autre date.")
            return render(request, 'reserver.html', {'document': document})

        # Créer la réservation
        Reservation.objects.create(
            utilisateur=request.user,
            document=document,
            date_venue=date_venue
        )
        messages.success(request, "Réservation confirmée !")
        return redirect('documents')

    return render(request, 'reserver.html', {'document': document})

# Page de gestion des réservations de l'utilisateur
@login_required
def mes_reservations(request):
    if not abonnement_valide(request.user):
        messages.error(request, "Votre abonnement n'est pas encore activé. Merci de venir à la médiathèque.")
        return redirect('accueil')
    
    reservations = Reservation.objects.filter(utilisateur=request.user).order_by('date_venue')
    return render(request, 'mes_reservations.html', {'reservations': reservations})

# Possibilité d'annuler une réservation
@login_required
def annuler_reservation(request, reservation_id):
    try:
        reservation = Reservation.objects.get(id=reservation_id, utilisateur=request.user)
        reservation.delete()
        messages.success(request, "Réservation annulée avec succès.")
    except Reservation.DoesNotExist:
        messages.error(request, "Réservation introuvable.")

    return redirect('mes_reservations')

# Information sur le compte utilisateur
@login_required
def mon_compte(request):
    try:
        profil = ProfilUtilisateur.objects.get(user=request.user)
    except ProfilUtilisateur.DoesNotExist:
        messages.error(request, "Profil introuvable.")
        return redirect('accueil')

    # Calcul de la prochaine date de cotisation de l'abonement 
    date_renouvellement = profil.date_abonnement.replace(year=profil.date_abonnement.year + 1)
    aujourd_hui = timezone.now().date()

    emprunts = Emprunt.objects.filter(utilisateur=request.user).order_by('-date_emprunt')
    
    # Statut abonnement et lettre de rappel envoyé 
    abonnement_en_retard = aujourd_hui > date_renouvellement and not profil.lettre_envoyee

    return render(request, 'mon_compte.html', {
        'profil': profil,
        'date_renouvellement': date_renouvellement,
        'abonnement_en_retard': abonnement_en_retard,
        'emprunts': emprunts, 
    })

gestion/templates/accueil.html
{# Page d'accueil du site de la médiathèque visible par tout le monde, même les personnes non connectées #}

{% extends "base.html" %}

{% block title %}Accueil - Médiathèque de Montpellier{% endblock %}

{% block content %}

{% load static %}

<h1>Bienvenue à la Médiathèque de Montpellier</h1>
<img src="{% static 'media/mediatheque.jpg' %}" alt="Photo de la médiathèque" class="image-large">


<p>Venez découvrir notre espace culturel, où vous pouvez emprunter des livres, CD, DVD, consulter des magazines, réserver des créneaux de prêt en ligne et gérer votre compte d’abonné.
    Nous sommes disponibles pour vous aider à trouver le document que vous cherchez et vous conseiller sur nos pépites.</p>
</p>

<hr>

<h2> Adresse</h2>
<p> 50 Allée Antoine de Saint-Exupéry<br>
34000 Montpellier</p>

<h2>🕒 Horaires d'ouverture</h2>
<table>
    <tr><th>Jour</th><th>Horaires</th></tr>
    <tr><td>Lundi</td><td>Fermé </td></tr>
    <tr><td>Mardi</td><td>10h – 18h</td></tr>
    <tr><td>Mercredi</td><td>10h – 18h</td></tr>
    <tr><td>Jeudi</td><td>10h – 18h</td></tr>
    <tr><td>Vendredi</td><td>14h – 18h</td></tr>
    <tr><td>Samedi</td><td>10h – 18h</td></tr>
    <tr><td>Dimanche</td><td>Fermé</td></tr>
</table>

<hr>

{% endblock %}

gestion/templates/base.html
{# Barre de navigation communes à toutes les pages html #}

{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Médiathèque de Montpellier{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
        {% if messages %}
            <div class="messages">
                {% for message in messages %}
                    <div class="alert {{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}    
    <header>
        <nav>
            {% if user.is_authenticated %}
                {% if user.is_staff %}
{# Pour les administrateurs #}
                    <a href="/">Accueil</a>
                    <a href="/admin/">Connexion Admin</a>
                    <a href="/deconnexion/">Déconnexion</a>
                {% else %}
{# Pour les inscrits #}
                    <a href="/">Accueil</a>
                    <a href="/contact/">Contact</a>
                    <a href="/documents/">Documents</a>
                    <a href="/mes_reservations/">Mes Réservations</a>
        
                    {% with user.profilutilisateur as profil %}
                        {% if profil.abonnement_valide %}
                            <a href="/mon_compte/">Mon Compte</a>
                        {% endif %}
                    {% endwith %}
        
                    <a href="/deconnexion/">Déconnexion</a>
                {% endif %}
            {% else %}

{# Pour les personnes non connectés #}
                <a href="/">Accueil</a>
                <a href="/contact/">Contact</a>
                <a href="/documents/">Documents</a>
                <a href="/connexion/">Connexion</a>
                <a href="/inscription/">Inscription</a>
                <a href="/admin/">Connexion Admin</a>
            {% endif %}
        </nav>
    </header>


 {# Si un utilisateur s'est inscrit mais n'est pas encore abonné, alors il voit ce message d'erreur sur toutes les pages car il n'a pas payé sa cotisation #}
 
    {% if user.is_authenticated %}
    {% if not user.is_staff %}
        {% with user.profilutilisateur as profil %}
            {% if not profil.abonnement_valide %}
                <div style="background-color: #ffdddd; color: #aa0000; padding: 15px; border: 1px solid red; margin: 0 20px 10px 20px; text-align: center;">
                    Attention!  Votre abonnement n'est pas encore validé.<br>
                    Merci de vous rendre à la médiathèque pour régler votre cotisation afin de profiter de toutes les fonctionnalités du site.
                </div>
            {% endif %}
        {% endwith %}
    {% endif %}
{% endif %}

    <main>
        {% block content %}{% endblock %}
    </main>

</body>
</html>

gestion/templates/connexion.html
{% extends "base.html" %}

{% block title %}Connexion - Médiathèque{% endblock %}

{% block content %}

        <h1>Connexion</h1>
        {% if messages %}
            {% for message in messages %}
                <p style="color: red;">{{ message }}</p>
            {% endfor %}
        {% endif %}

        <form method="POST" action="/connexion/">
            {% csrf_token %}
            <label for="email">Adresse Email :</label>
            <input type="email" id="email" name="email" required><br>

            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required><br>

            <button type="submit">Se connecter</button>
        </form>
        
{% endblock %}

{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}

gestion/templates/contact.html
{% extends "base.html" %}

{% block title %}Contact - Médiathèque{% endblock %}

{% block content %}

<body>
    <h1>Contactez-nous</h1>
    <p>Adresse : 50 Allée Antoine de Saint-Exupéry<br>
        34000 Montpellier</p>
    <p>Téléphone : 04 67 28 00 89</p>
</body>

{% endblock %}
{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}

gestion/templates/documents.html
{% extends "base.html" %}

{% block title %}Documents - Médiathèque{% endblock %}

{% block content %}
    <main>
        <h1>Catalogue des documents</h1>

{# Filtrage pour rechercher documents #}
        <form method="get">
            <label>Type :</label>
            <select name="type_document">
                <option value="">Tous</option>
                <option value="livre">Livre imprimé</option>
                <option value="cd">CD audio</option>
                <option value="dvd">DVD / Blu-Ray</option>
                <option value="magazine">Magazine</option>
            </select>

            <label>Auteur :</label>
            <input type="text" name="auteur" placeholder="Nom de l'auteur">

            <label>Genre :</label>
            <input type="text" name="genre" placeholder="Genre (roman, thriller...)">

            <label for="date_choisie">Filtrer par date d'emprunt souhaitée :</label>
            <input type="date" id="date_choisie" name="date_choisie" value="{{ date_choisie }}">
            <br>

            <label>Date de sortie après :</label>
            <input type="date" name="date_min">

            <label>Durée maximale (minutes) :</label>
            <input type="number" name="duree_max" placeholder="Durée max en minutes">

            <button type="submit">Filtrer</button>
        </form>
        <br>

        <table border="1">
            <tr>
                <th>Titre</th>
                <th>Auteur</th>
                <th>Type</th>
                <th>Genre</th>
                <th>Disponibilité</th>
                <th>Nombre de pages</th>
                <th>Durée (minutes)</th>
                <th>Date de sortie</th>

            </tr>

            {% for info in documents_info %}
                <tr>
                    <td>{{ info.document.titre }}</td>
                    <td>{{ info.document.auteur }}</td>
                    <td>{{ info.document.get_type_document_display }}</td>
                    <td>{{ info.document.genre }}</td>
                    <td>
{# si le document est disponible, le bouton réserver apparait, sinon impossible de réserver #}
                        {% if user.is_authenticated and abonnement_valide and info.disponible %}
                        <form method="get" action="{% url 'reserver_document' info.document.id %}">
                            <input type="hidden" name="date_venue" value="{{ date_choisie }}">
                            <button type="submit">Réserver</button>
                        </form>
                        {% else %}
                            Déjà réservé 
                        {% endif %}
                    </td>
                    <td>
                        {% if info.document.nombre_pages %}
                            {{ info.document.nombre_pages }} pages
                        {% else %}
                            -
                        {% endif %}
                    </td>
                
                    <td>
                        {% if info.document.duree_minutes %}
                            {{ info.document.duree_minutes }} min
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    
                    <td>
                        {% if info.document.date_sortie %}
                            {{ info.document.date_sortie }}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>

    </main>
</body>

{% endblock %}
{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}

gestion/templates/inscription.html
{% extends "base.html" %}

{% block title %}Documents - Médiathèque{% endblock %}

{% block content %}

    <main>
        <h1>Inscription</h1>
        <form method="POST" action="/inscription/">
            {% csrf_token %}
            <label for="first_name">Prénom :</label>
            <input type="text" id="first_name" name="first_name" required><br>

            <label for="last_name">Nom :</label>
            <input type="text" id="last_name" name="last_name" required><br>

            <label for="date_naissance">Date de naissance :</label>
            <input type="date" name="date_naissance" required><br>

            <label for="ville">Ville :</label>
            <input type="text" name="ville" required><br>

            <label for="etudiant ">Scolarisé </label>
            <input type="checkbox" name="etudiant"><br>

            <label for="email">Adresse Email :</label>
            <input type="email" id="email" name="email" required><br>

            <label for="password">Mot de passe :</label>
            <input type="password" id="password" name="password" required><br>

            <button type="submit">S'inscrire</button>
        </form>
    </main>
</body>
</html>
{% endblock %}

{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}

gestion/templates/mes_reservations.html
{% extends "base.html" %}

{% block title %}Documents - Médiathèque{% endblock %}

{% block content %}
<body>

<h1>Mes Réservations</h1>

{% if reservations %}
    <table border="1">
        <tr>
            <th>Document</th>
            <th>Date de venue</th>
            <th>Action</th>
        </tr>
        {% for resa in reservations %}
        <tr>
            <td>{{ resa.document.titre }}</td>
            <td>{{ resa.date_venue }}</td>
            <td>
                <form method="post" action="{% url 'annuler_reservation' resa.id %}">
                    {% csrf_token %}
                    <button type="submit">Annuler</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Vous n'avez aucune réservation.</p>
{% endif %}

<a href="/documents/">Retour aux documents</a>

</body>
</html>
{% endblock %}

{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}

gestion/templates/mon_compte.html
{% extends "base.html" %}

{% block title %}Documents - Médiathèque{% endblock %}

{% block content %}

<h1>Mon compte</h1>

<p><strong>Nom :</strong> {{ profil.user.first_name }} {{ profil.user.last_name }}</p>
<p><strong>Email :</strong> {{ profil.user.email }}</p>
<h3>Coût de l’abonnement :</h3>
<p>
    {% if profil.est_gratuit %}
        Votre abonnement est gratuit.
    {% else %}
        tarif normal : 22 € par an ou tarif réduit : 10,50 € par mois
    {% endif %}
</p>

<p><strong>Date d’abonnement :</strong> {{ profil.date_abonnement }}</p>

<p><strong>Date de renouvellement :</strong> {{ date_renouvellement }}</p>
{% if profil.abonnement_valide %}
    <p style="color: green;"><strong>Abonnement :</strong> À jour </p>
{% else %}
    <p style="color: red;"><strong>Abonnement :</strong> Non valide </p>
{% endif %}

{% if abonnement_en_retard %}
    <p style="color: red;"><strong>Rappel :</strong> Une lettre de rappel a été envoyée </p>
{% elif profil.lettre_envoyee %}
    <p style="color: orange;"><strong>Rappel :</strong> Lettre de rappel envoyée</p>
{% else %}
    <p><strong>Rappel :</strong> Aucun rappel envoyé</p>
{% endif %}

{% if emprunts %}
    <table>
        <tr>
            <th>Document</th>
            <th>Date d’emprunt</th>
            <th>Date retour prévue</th>
            <th>Date retour réelle</th>
            <th>Statut</th>
        </tr>
        {% for emprunt in emprunts %}
        <tr>
            <td>{{ emprunt.document.titre }}</td>
            <td>{{ emprunt.date_emprunt }}</td>
            <td>{{ emprunt.date_retour_prevue }}</td>
            <td>{{ emprunt.date_retour_reelle|default:"—" }}</td>
            <td>
                {% if emprunt.date_retour_reelle %}
                    ✅ Rendu
                {% elif emprunt.date_retour_prevue < today %}
                    🔴 En retard
                {% else %}
                    ⏳ En cours
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Vous n’avez pas encore emprunté de document.</p>
{% endif %}


{% endblock %}

gestion/templates/reserver.html
{% extends "base.html" %}

{% block title %}Documents - Médiathèque{% endblock %}

{% block content %}

    <title>Réserver - {{ document.titre }}</title>

<body>
    {% if messages %}
    {% for message in messages %}
        <p style="color: red;">{{ message }}</p>
    {% endfor %}
{% endif %}

    <h1>Réserver : {{ document.titre }}</h1>

    <form method="POST">
        {% csrf_token %}
        <label for="date_venue">Choisir votre date de venue :</label>
        <input type="date" id="date_venue" name="date_venue" required><br><br>

        <button type="submit">Valider la réservation</button>
    </form>

    <a href="/documents/">Retour au documents</a>

</body>
</html>
{% endblock %}

{% block footer %}
    <footer>
        <p>&copy; 2025 Médiathèque</p>
    </footer>
{% endblock %}